DAQ-3779 Bring spring profile handling into line with client
Remove the need to have an = sign when specifying spring profiles and
also block profiles called "servers", "client", "logpanel", or beginning
with "-" or "--".

Change-Id: I39a93f034cb3dd52a7f4185268d7eac9dc908355

diff --git a/core-config/bin/gda_servers_core b/core-config/bin/gda_servers_core
--- a/core-config/bin/gda_servers_core
+++ b/core-config/bin/gda_servers_core
@@ -8,28 +8,43 @@ readonly ABORTED=66
 readonly FAILED=99
 
 # read the GDA9 specific params
-for word in "$@"; do
-    case $word in
+while [[ "$#" != 0 ]]; do
+  case "$1" in
         -d|--debug)
+            shift
             DEBUG="--debug"
             options_text+="\nUse debugger connection on port 8000"
             ;;
         -b|--debug-wait)
+            shift
             DEBUG="--debug-wait"
             options_text+="\nAwaiting debugger connection on port 8000"
             ;;
         -j|--jrebel)
+            shift
             GDA_ARGS+="--jrebel "
             ;;
-        --springprofiles=*)
-            export SPRING_PROFILES="${word:17}"
-            GDA_ARGS+="${word} "
+        --springprofiles)
+            shift
+            if [[ -n "$1" && $1 != "servers" && $1 != "client" && $1 != "logpanel" && $1 != "-"* ]]; then
+                export SPRING_PROFILES="${1}"
+                GDA_ARGS+="--springprofiles ${1} "
+                shift
+            else
+                echo -e "${options_text}""\n\e[31mERROR: Incorrect Spring profile specification\e[0m"
+                exit $FAILED
+            fi
             ;;
         --force)
+            shift
             options_text+="\n\e[33mWARNING: The --force option is no longer necessary or supported; please remove it from your startup scripts\e[0m"
             ;;
+        --)
+            shift
+            break;
+            ;;
         *)
-            continue
+            shift
             ;;
     esac
 done
